export default [
  {
    name: 'Санкт-Петербург',
    address: 'Россия',
    category: 'Rossiya',
    coords: '59.940224,30.308533',
    id: 'Saint-Petersburg',
  },
  {
    name: 'Москва',
    address: 'Россия',
    category: 'Rossiya',
    coords: '55.7447,37.6728',
    id: 'Moskva',
  },
  {
    name: 'Sydney',
    address: 'Австралия',
    category: 'Cities-of-the-World',
    coords: '-33.847608,150.930176',
    id: 'Sydney',
  },
  {
    name: 'NewYork',
    address: 'США',
    category: 'Cities-of-the-World',
    coords: '40.711353,-74.002533',
    id: 'NewYork',
  },
  {
    name: 'London',
    address: 'Великобритания',
    category: 'Cities-of-the-World',
    coords: '51.510452,-0.127716',
    id: 'London',
  },
  {
    name: 'Berlin',
    address: 'Германия',
    category: 'Cities-of-the-World',
    coords: '52.5045,13.4383',
    id: 'Berlin',
  },
  {
    name: 'Пекин',
    address: 'Китай',
    category: 'Cities-of-the-World',
    coords: '39.9182,116.4551',
    id: 'Pekin',
  },

  {
    name: 'Донецк',
    address: 'Украина',
    category: 'Ukraina',
    coords: '47.9957,37.8592',
    id: 'Donetsk',
  },
  {
    name: 'Харьков',
    address: 'Украина',
    category: 'Ukraina',
    coords: '49.9968,36.2429',
    id: 'Kharkiv',
  },
  {
    name: 'Львов',
    address: 'Украина',
    category: 'Ukraina',
    coords: '49.8205,24.0549',
    id: 'Lvov',
  },
  {
    name: 'Перекоповка',
    address: 'Сумская обл.',
    category: 'Ukraina',
    coords: '50.605, 33.425',
    id: 'Perekopovka',
    zoom: '13',
  },
  {
    name: 'Керченский пролив',
    address: 'Крым',
    coords: '45.286,36.5549',
    id: 'Kerchenskij-proliv',
  },
];
