export default [
  { name: 'Cities of the World', id: 'Cities-of-the-World' },
  { name: 'Украина', id: 'Ukraina' },
  { name: 'Россия', id: 'Rossiya' },
  { name: 'Bosnia and Herzegovina', id: 'Bosnia-and-Herzegovina' },
  { name: 'Portugal', id: 'Portugal' },
  { name: 'Philippines', id: 'Philippines' },
  { name: 'Brazil', id: 'Brazil' },
  { name: 'Warcraft' },
  { name: 'Brazilian', id: 'Brazil' },
  { id: 'megafack' },
  { name: 'Африка', id: 'Afrika' },
  null,
  {},
  { name: 'Озера', id: 'Ozera' },
  [],
  100500,
  'Zdrasti',
];
