export default {
  app: {
    currentLocale: 'en',
    defaultLocale: 'en',
    locales: ['en', 'ru', 'ua'],
  },
  a_countries: [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
  ],
  continents: [
    'Asia',
    'Africa',
    'North America',
    'South America',
    'Antarctica',
    'Europe',
    'Australia',
  ],
  categories: require('./__data/categories').default,
  locations: require('./__data/locations').default,
  presidents: require('./__data/presidents').default,
};
